name: Codecov Workflow

on: [push, pull_request]

env:
  TEST_API_SECRET: ${{ secrets.TEST_API_SECRET }}
  TEST_API_CLIENT_ID: ${{ secrets.TEST_API_CLIENT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test coverage upload
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install requirements
      run: pip install -r finrashortdata/requirements/dev.txt
    - name: Run tests and collect coverage
      run: pytest --cov --cov-config=.coveragerc .
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3